k8s_cluster: k8s-master-1 k8s-master-2 k8s-master-3
LB_IP: 10.28.20.128
KUBE_APISERVER: https://{{LB_IP}}:6443
SERVICE_CIDR: 10.244.0.0/16
CLUSTER_CIDR: 10.96.0.0/16
CLUSTER_KUBERNETES_SVC_IP: 10.244.0.1
CLUSTER_DNS_SVC_IP: 10.244.0.2
NODE_PORT_RANGE: 20000-50000
CLUSTER_DNS_DOMAIN: cluster.local.
ETCD_NODES: k8s-master-1=https://k8s-master-1:2380,k8s-master-2=https://k8s-master-2:2380,k8s-master-3=https://k8s-master-3:2380
ETCD_ENDPOINTS: https://k8s-master-1:2379,https://k8s-master-2:2379,https://k8s-master-3:2379

k8s_dir: /etc/kubernetes/
k8s_manifests_dir: /etc/kubernetes/manifests/
ca_dir: /etc/kubernetes/ssl/
etcd_dir: /etc/etcd/
etcd_ca_dir: /etc/etcd/ssl/
etcd_lib_dir: /var/lib/etcd/
calico_dir: /etc/calico/
calico_log: /var/log/calico
cni_dir: /etc/cni/net.d/
kubelet_lib_dir: /var/lib/kubelet/
kube_proxy_lib_dir: /var/lib/kube-proxy/
docker_dir: /etc/docker/
DAOCLOUD: http://61838238.m.daocloud.io

HARBOR_DOMAIN: k8s-harbor.test.fruitday.com
HARBOR_DB_PASSWORD: fruitday@888
HARBOR_ADMIN_PASSWORD: Harbor12345


# BASIC_AUTH_USER 账号密码验证功能，需修改basic-auth.csv
BASIC_AUTH_USER: admin
# BASIC_AUTH_PASS admin.p12 密码
