apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: prometheus-operator
