apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-controller-manager
  labels:
    app: kube-controller-manager
spec:
  jobLabel: app
  endpoints:
  - port: http-metrics
    interval: 30s
  selector:
    matchLabels:
      app: kube-controller-manager
  namespaceSelector:
    matchNames:
    - kube-system
