apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers :
  - name: kube-apiserver
    image: njqaaa/kube-apiserver-amd64:v1.8.5
    command:
      - kube-apiserver
      - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction 
      - --bind-address={{ ansible_default_ipv4.address }} 
      - --insecure-bind-address=127.0.0.1 
      - --authorization-mode=Node,RBAC 
      - --kubelet-https=true 
      - --anonymous-auth=false 
      - --basic-auth-file={{ ca_dir }}basic-auth.csv 
      - --enable-bootstrap-token-auth 
      - --token-auth-file={{ ca_dir }}token.csv 
      - --service-cluster-ip-range={{ SERVICE_CIDR }} 
      - --service-node-port-range={{ NODE_PORT_RANGE }} 
      - --tls-cert-file={{ ca_dir }}kubernetes.pem 
      - --tls-private-key-file={{ ca_dir }}kubernetes-key.pem 
      - --client-ca-file={{ ca_dir }}ca.pem 
      - --service-account-key-file={{ ca_dir }}ca-key.pem 
      - --etcd-cafile={{ ca_dir }}ca.pem 
      - --etcd-certfile={{ etcd_ca_dir }}etcd.pem 
      - --etcd-keyfile={{ etcd_ca_dir }}etcd-key.pem 
      - --etcd-servers={{ ETCD_ENDPOINTS }} 
      - --enable-swagger-ui=true 
      - --allow-privileged=true 
      - --audit-log-maxage=30 
      - --audit-log-maxbackup=3 
      - --audit-log-maxsize=100 
      - --audit-log-path=/var/log/audit.log 
      - --event-ttl=1h 
      - --v=2
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /var/log/audit.log
      name: k8s-audit-log
    - mountPath: {{ ca_dir }}
      name: k8s-certs
      readOnly: true
    - mountPath: {{ etcd_ca_dir }}
      name: etcd-certs
      readOnly: true
    - mountPath: /etc/localtime
      name: tz-config
      readOnly: true
  volumes:
  - hostPath:
      path: /var/log/audit.log
      type: FileOrCreate
    name: k8s-audit-log
  - hostPath:
      path: {{ ca_dir }}
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: {{ etcd_ca_dir }}
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /usr/share/zoneinfo/Asia/Shanghai
      type: FileOrCreate
    name: tz-config
