apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: njqaaa/kube-controller-manager-amd64:v1.8.5
    command:
      - kube-controller-manager
      - --address=127.0.0.1
      - --master=http://127.0.0.1:8080
      - --allocate-node-cidrs=true
      - --service-cluster-ip-range={{ SERVICE_CIDR }}
      - --cluster-cidr={{ CLUSTER_CIDR }}
      - --cluster-name=kubernetes
      - --cluster-signing-cert-file={{ ca_dir }}ca.pem
      - --cluster-signing-key-file={{ ca_dir }}ca-key.pem
      - --service-account-private-key-file={{ ca_dir }}ca-key.pem
      - --root-ca-file={{ ca_dir }}ca.pem \
      - --leader-elect=true \
      - --v=2
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        cpu: 200m
    volumeMounts:
    - mountPath: {{ ca_dir }}
      name: k8s-certs
      readOnly: true
    - mountPath: /etc/localtime
      name: tz-config
      readOnly: true
  volumes:
  - hostPath:
      path: {{ ca_dir }} 
      type: DirectoryOrCreate
    name: k8s-certs
  - hostPath:
      path: /usr/share/zoneinfo/Asia/Shanghai
      type: FileOrCreate
    name: tz-config
