apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    type: storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.28.201.72:6789
    pool: harbor
    image: storage
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
