- name: initialize dir
  file: name={{ item }} state=directory mode=0755
  with_items:
  - "{{ java_dir }}"

- name: sync jdk
  synchronize: src=dir/{{ item }} dest={{ java_dir }}
  with_items:
  - "jdk"

- name:  ln -sf {{ java_dir }}/jdk/bin/java /usr/bin/java
  shell: ln -sf {{ java_dir }}/jdk/bin/java /usr/bin/java

- name:  sync env
  template: src=env/{{ item }} dest=/etc/profile.d/{{ item }}
  with_items:
  - "jdk.sh"

- name: add {{ es_user }}
  user: name={{ es_user }} shell=/bin/bash append=yes

- name: sync es
  synchronize: src=dir/{{ item }} dest=/opt
  with_items:
  - "elasticsearch"
  - "elasticsearch-head"
  - "bigdesk"

- name:  sync config
  template: src=config/{{ item }} dest={{ es_dir }}config/{{ item }}
  with_items:
  - "elasticsearch.yml"

- name: delete bat
  shell: find {{ item }} -name *.bat |xargs rm
  with_items:
  - "{{ es_dir }}"
  ignore_errors: true

- name: sync limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: sync sysctl es.conf
  copy: src=sysctl.d/es.conf dest=/etc/sysctl.d/es.conf

- name: sysctl -p /etc/sysctl.d/es.conf
  shell: sysctl -p /etc/sysctl.d/es.conf

- name: directory owner for {{ es_user }}
  file: name={{ item }} state=directory mode=0755 owner={{ es_user }} group={{ es_user }} recurse=yes
  with_items:
  - "{{ es_dir }}"
  - "{{ es_head_dir }}"
  - "{{ es_bigdesk_dir }}"

- name: start es
  shell: su - es -c "{{ es_dir }}bin/elasticsearch -d"
