kind: ConfigMap
apiVersion: v1
metadata:
  name: kibana-config
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  kibana.yml: |-
    #server.port: 5601
    server.host: "0.0.0.0"
    #server.basePath: ""
    #server.maxPayloadBytes: 1048576
    #server.name: "your-hostname"

    elasticsearch.url: "http://{{ LB_IP }}:9200"
    #elasticsearch.preserveHost: true

    #kibana.index: ".kibana"
    #kibana.defaultAppId: "home"

    #elasticsearch.username: "user"
    #elasticsearch.password: "pass"
    
    #server.ssl.enabled: false
    #server.ssl.certificate: /path/to/your/server.crt
    #server.ssl.key: /path/to/your/server.key
    
    #elasticsearch.ssl.certificate: /path/to/your/client.crt
    #elasticsearch.ssl.key: /path/to/your/client.key
    #elasticsearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]
    #elasticsearch.ssl.verificationMode: full
    #elasticsearch.pingTimeout: 1500
    #elasticsearch.requestTimeout: 30000
    #elasticsearch.requestHeadersWhitelist: [ authorization ]
    #elasticsearch.customHeaders: {}
    #elasticsearch.shardTimeout: 0
    #elasticsearch.startupTimeout: 5000

    #pid.file: /var/run/kibana.pid

    #logging.dest: stdout
    #logging.silent: false
    #logging.quiet: false
    #logging.verbose: false

    #ops.interval: 5000
    #i18n.defaultLocale: "en"
