# 集群名
cluster.name: fruitday-es-test

# 节点名
node.name: {{ ansible_hostname }}

# 指定该节点是否有资格被选举成为master，默认为true。
node.master: true

# 指定该节点是否存储索引数据，默认为true。
node.data: true

# 设置默认索引分片个数，默认为5片。
# index.number_of_shards: 5

# 设置默认索引副本个数，默认为1个副本。
# index.number_of_replicas: 1

# 设置索引数据的存储路径，默认是es根目录下的data文件夹，
#path.data: /path/to/data

# 设置日志文件的存储路径，默认是es根目录下的logs文件夹
#path.logs: /path/to/logs

network.host: {{ ansible_default_ipv4.address }}
network.bind_host: {{ ansible_default_ipv4.address }}
network.publish_host: {{ ansible_default_ipv4.address }}

http.port: 9200
transport.tcp.port: 9300

# 设置内容的最大容量，默认100mb
http.max_content_length: 100mb

# 是否使用http协议对外提供服务，默认为true，开启。
#http.enabled: true
#
http.cors.enabled: true
http.cors.allow-origin: "*"

# gateway的类型，默认为local即为本地文件系统，
# gateway.type: local

# 设置这个集群中节点的数量，默认为2，一旦这N个节点启动，就会立即进行数据恢复。
gateway.expected_nodes: 3

discovery.zen.ping.unicast.hosts: ["es-1", "es-2","es-3"]

discovery.zen.minimum_master_nodes: 2

# Lock the memory on startup:
#
#bootstrap.memory_lock: true
